# Generated by Django 5.2.6 on 2025-09-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product_category_product_description_product_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='pk',
            field=models.CompositePrimaryKey('order_id', 'product_id', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='id',
        ),
    ]
